### ISSUE TITLE
File support

### ISSUE THREAD

**Issue by Log1x** [atakde/discord-webhook-php#2]
A `FileMessage` class would be excellent.

The main thing that needs to be done is a file needs to be attached to `file` and the header needs to change from JSON to [`multipart/form-data`](https://gist.github.com/supernovaplus/4e1056aa928c273dc82a449681daee61#file-discord_webhook_upload_file-php-L26).

It could get fancy and have an easy way to attach a text-based attachment, but otherwise most of it could be left up to the user.

**Comment by atakde** [comment]
A new class FileMessage is available.

Thanks for your feedbacks.
