### ISSUE TITLE
Remove `echo` when exception is thrown

### ISSUE THREAD

**Issue by Log1x** [atakde/discord-webhook-php#3]
Any chance of removing the `echo` when [an exception is thrown](https://github.com/atakde/discord-webhook-php/blob/master/src/DiscordWebhook.php#L61)?

Forcing output is typically not ideal and it is clashing with my error handler in Laravel. Leaving it as a bool would be great so it'd be up to the user to decide if an exception should be thrown or how it should be handled.

**Comment by atakde** [comment]
Thanks for reporting, I added a debug mode, and the default return type without the debug mode is bool.
