### ISSUE TITLE
Using old PHP

### ISSUE THREAD

**Issue by poejanetwork** [atakde/discord-webhook-php#4]
I'm using old PHP (7.4) and cannot do "composer require atakde/discord-webhook-php" it will return error
Cannot use atakde/discord-webhook-php's latest version 2.0.0 as it requires php >=8.0.9 which is not satisfied by your platform.

any fix?

**Comment by atakde** [comment]
Hey, can you please try this;

```php
composer require atakde/discord-webhook-php:1.0.0
```
